export const DOG_BREEDS = [
  'Labrador Retriever',
  'Golden Retriever',
  'Pastor Alemán',
  'Bulldog Francés',
  'Bulldog Inglés',
  'Beagle',
  'Poodle',
  'Rottweiler',
  'Yorkshire Terrier',
  'Boxer',
  'Dachshund (Salchicha)',
  'Husky Siberiano',
  'Pomerania',
  'Chihuahua',
  'Shih Tzu',
  'Doberman',
  'Schnauzer',
  'Boston Terrier',
  'Cocker Spaniel',
  'Bichón Frisé',
  'Maltés',
  'Pug (Carlino)',
  'Border Collie',
  'Akita',
  'Chow Chow',
  'Dálmata',
  'Gran Danés',
  'Basset Hound',
  'San Bernardo',
  'Weimaraner',
  'Jack Russell Terrier',
  'Pitbull',
  'American Bully',
  'Staffordshire Bull Terrier',
  'Galgo',
  'Mastín',
  'Podenco',
  'Bodeguero Andaluz',
  'Mestizo',
  'Otro',
].sort();
